# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1366, 768)
        MainWindow.setAcceptDrops(False)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.treeView = QtWidgets.QTreeView(self.centralwidget)
        self.treeView.setGeometry(QtCore.QRect(0, 0, 256, 741))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeView.sizePolicy().hasHeightForWidth())
        self.treeView.setSizePolicy(sizePolicy)
        self.treeView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.treeView.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.treeView.setObjectName("treeView")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(260, 0, 1101, 741))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1366, 28))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuMetrics = QtWidgets.QMenu(self.menubar)
        self.menuMetrics.setObjectName("menuMetrics")
        self.menuFunction_Points = QtWidgets.QMenu(self.menuMetrics)
        self.menuFunction_Points.setObjectName("menuFunction_Points")
        self.menuUse_Case_Points = QtWidgets.QMenu(self.menuMetrics)
        self.menuUse_Case_Points.setObjectName("menuUse_Case_Points")
        self.menuSMI = QtWidgets.QMenu(self.menuMetrics)
        self.menuSMI.setObjectName("menuSMI")
        self.menuProject_code = QtWidgets.QMenu(self.menubar)
        self.menuProject_code.setObjectName("menuProject_code")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuPreferences = QtWidgets.QMenu(self.menubar)
        self.menuPreferences.setObjectName("menuPreferences")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.actionLanguage = QtWidgets.QAction(MainWindow)
        self.actionLanguage.setObjectName("actionLanguage")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionSMI = QtWidgets.QAction(MainWindow)
        self.actionSMI.setObjectName("actionSMI")
        self.actionOO_Metrics = QtWidgets.QAction(MainWindow)
        self.actionOO_Metrics.setObjectName("actionOO_Metrics")
        self.actionEnter_FP_Data = QtWidgets.QAction(MainWindow)
        self.actionEnter_FP_Data.setObjectName("actionEnter_FP_Data")
        self.actionCompute_Code_Size = QtWidgets.QAction(MainWindow)
        self.actionCompute_Code_Size.setObjectName("actionCompute_Code_Size")
        self.actionAdd_Code = QtWidgets.QAction(MainWindow)
        self.actionAdd_Code.setObjectName("actionAdd_Code")
        self.actionProject_Code_Statistics = QtWidgets.QAction(MainWindow)
        self.actionProject_Code_Statistics.setObjectName("actionProject_Code_Statistics")
        self.actionEnter_UCP_data = QtWidgets.QAction(MainWindow)
        self.actionEnter_UCP_data.setObjectName("actionEnter_UCP_data")
        self.actionEnter_SMI_data = QtWidgets.QAction(MainWindow)
        self.actionEnter_SMI_data.setObjectName("actionEnter_SMI_data")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionExit)
        self.menuFunction_Points.addAction(self.actionEnter_FP_Data)
        self.menuFunction_Points.addAction(self.actionCompute_Code_Size)
        self.menuUse_Case_Points.addAction(self.actionEnter_UCP_data)
        self.menuSMI.addAction(self.actionEnter_SMI_data)
        self.menuMetrics.addAction(self.menuFunction_Points.menuAction())
        self.menuMetrics.addAction(self.menuUse_Case_Points.menuAction())
        self.menuMetrics.addAction(self.menuSMI.menuAction())
        self.menuProject_code.addAction(self.actionAdd_Code)
        self.menuProject_code.addAction(self.actionProject_Code_Statistics)
        self.menuPreferences.addAction(self.actionLanguage)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuPreferences.menuAction())
        self.menubar.addAction(self.menuMetrics.menuAction())
        self.menubar.addAction(self.menuProject_code.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CECS 543 Metrics Suite"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuMetrics.setTitle(_translate("MainWindow", "Metrics"))
        self.menuFunction_Points.setTitle(_translate("MainWindow", "Function Points"))
        self.menuUse_Case_Points.setTitle(_translate("MainWindow", "Use Case Points"))
        self.menuSMI.setTitle(_translate("MainWindow", "SMI"))
        self.menuProject_code.setTitle(_translate("MainWindow", "Project code"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuPreferences.setTitle(_translate("MainWindow", "Preferences"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.actionLanguage.setText(_translate("MainWindow", "Language"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionSMI.setText(_translate("MainWindow", "SMI"))
        self.actionOO_Metrics.setText(_translate("MainWindow", "OO Metrics"))
        self.actionEnter_FP_Data.setText(_translate("MainWindow", "Enter FP Data"))
        self.actionCompute_Code_Size.setText(_translate("MainWindow", "Compute Code Size"))
        self.actionAdd_Code.setText(_translate("MainWindow", "Add Code"))
        self.actionProject_Code_Statistics.setText(_translate("MainWindow", "Project Code Statistics"))
        self.actionEnter_UCP_data.setText(_translate("MainWindow", "Enter UCP data"))
        self.actionEnter_SMI_data.setText(_translate("MainWindow", "Enter SMI data"))
