# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/tcf_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1366, 768)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 903, 581))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.label_73 = QtWidgets.QLabel(self.layoutWidget)
        self.label_73.setObjectName("label_73")
        self.gridLayout.addWidget(self.label_73, 13, 1, 1, 1)
        self.label_68 = QtWidgets.QLabel(self.layoutWidget)
        self.label_68.setObjectName("label_68")
        self.gridLayout.addWidget(self.label_68, 12, 1, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 2, 2, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.layoutWidget)
        self.label_32.setObjectName("label_32")
        self.gridLayout.addWidget(self.label_32, 5, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 1, 0, 1, 1)
        self.label_72 = QtWidgets.QLabel(self.layoutWidget)
        self.label_72.setObjectName("label_72")
        self.gridLayout.addWidget(self.label_72, 13, 0, 1, 1)
        self.label_67 = QtWidgets.QLabel(self.layoutWidget)
        self.label_67.setObjectName("label_67")
        self.gridLayout.addWidget(self.label_67, 12, 0, 1, 1)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_11.sizePolicy().hasHeightForWidth())
        self.lineEdit_11.setSizePolicy(sizePolicy)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout.addWidget(self.lineEdit_11, 11, 2, 1, 1)
        self.label_62 = QtWidgets.QLabel(self.layoutWidget)
        self.label_62.setObjectName("label_62")
        self.gridLayout.addWidget(self.label_62, 11, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 1, 1, 1, 1)
        self.label_63 = QtWidgets.QLabel(self.layoutWidget)
        self.label_63.setObjectName("label_63")
        self.gridLayout.addWidget(self.label_63, 11, 1, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 1, 3, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout.addWidget(self.comboBox_2, 2, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 14, 4, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.layoutWidget)
        self.label_43.setObjectName("label_43")
        self.gridLayout.addWidget(self.label_43, 7, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.layoutWidget)
        self.label_23.setObjectName("label_23")
        self.gridLayout.addWidget(self.label_23, 3, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.layoutWidget)
        self.label_27.setObjectName("label_27")
        self.gridLayout.addWidget(self.label_27, 4, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.layoutWidget)
        self.label_28.setObjectName("label_28")
        self.gridLayout.addWidget(self.label_28, 4, 1, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.layoutWidget)
        self.label_42.setObjectName("label_42")
        self.gridLayout.addWidget(self.label_42, 7, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.layoutWidget)
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 3, 0, 1, 1)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_9.sizePolicy().hasHeightForWidth())
        self.lineEdit_9.setSizePolicy(sizePolicy)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout.addWidget(self.lineEdit_9, 9, 2, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_10.sizePolicy().hasHeightForWidth())
        self.lineEdit_10.setSizePolicy(sizePolicy)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout.addWidget(self.lineEdit_10, 10, 2, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_7.sizePolicy().hasHeightForWidth())
        self.lineEdit_7.setSizePolicy(sizePolicy)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout.addWidget(self.lineEdit_7, 7, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 2, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_3.sizePolicy().hasHeightForWidth())
        self.lineEdit_3.setSizePolicy(sizePolicy)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 3, 2, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.layoutWidget)
        self.label_38.setObjectName("label_38")
        self.gridLayout.addWidget(self.label_38, 6, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 4, 1, 1)
        self.label_58 = QtWidgets.QLabel(self.layoutWidget)
        self.label_58.setObjectName("label_58")
        self.gridLayout.addWidget(self.label_58, 10, 1, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.layoutWidget)
        self.label_48.setObjectName("label_48")
        self.gridLayout.addWidget(self.label_48, 8, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.layoutWidget)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 7, 4, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.layoutWidget)
        self.label_24.setObjectName("label_24")
        self.gridLayout.addWidget(self.label_24, 8, 4, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.layoutWidget)
        self.label_25.setObjectName("label_25")
        self.gridLayout.addWidget(self.label_25, 9, 4, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.layoutWidget)
        self.label_29.setObjectName("label_29")
        self.gridLayout.addWidget(self.label_29, 10, 4, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.layoutWidget)
        self.label_30.setObjectName("label_30")
        self.gridLayout.addWidget(self.label_30, 11, 4, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.layoutWidget)
        self.label_34.setObjectName("label_34")
        self.gridLayout.addWidget(self.label_34, 12, 4, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.layoutWidget)
        self.label_35.setObjectName("label_35")
        self.gridLayout.addWidget(self.label_35, 13, 4, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.layoutWidget)
        self.label_52.setObjectName("label_52")
        self.gridLayout.addWidget(self.label_52, 9, 0, 1, 1)
        self.label_57 = QtWidgets.QLabel(self.layoutWidget)
        self.label_57.setObjectName("label_57")
        self.gridLayout.addWidget(self.label_57, 10, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 3, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_8.sizePolicy().hasHeightForWidth())
        self.lineEdit_8.setSizePolicy(sizePolicy)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout.addWidget(self.lineEdit_8, 8, 2, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.layoutWidget)
        self.label_47.setObjectName("label_47")
        self.gridLayout.addWidget(self.label_47, 8, 0, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.layoutWidget)
        self.label_33.setObjectName("label_33")
        self.gridLayout.addWidget(self.label_33, 5, 1, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_4.sizePolicy().hasHeightForWidth())
        self.lineEdit_4.setSizePolicy(sizePolicy)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 4, 2, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.layoutWidget)
        self.label_37.setObjectName("label_37")
        self.gridLayout.addWidget(self.label_37, 6, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.layoutWidget)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 2, 1, 1, 1)
        self.comboBox_11 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_11.setObjectName("comboBox_11")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.gridLayout.addWidget(self.comboBox_11, 11, 3, 1, 1)
        self.comboBox_12 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_12.setObjectName("comboBox_12")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.gridLayout.addWidget(self.comboBox_12, 12, 3, 1, 1)
        self.comboBox_13 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_13.setObjectName("comboBox_13")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.gridLayout.addWidget(self.comboBox_13, 13, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 4, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 2, 4, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 3, 4, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 4, 4, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 5, 4, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 6, 4, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_6.sizePolicy().hasHeightForWidth())
        self.lineEdit_6.setSizePolicy(sizePolicy)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout.addWidget(self.lineEdit_6, 6, 2, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.layoutWidget)
        self.label_53.setObjectName("label_53")
        self.gridLayout.addWidget(self.label_53, 9, 1, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.gridLayout.addWidget(self.comboBox_3, 3, 3, 1, 1)
        self.comboBox_4 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.gridLayout.addWidget(self.comboBox_4, 4, 3, 1, 1)
        self.comboBox_5 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.gridLayout.addWidget(self.comboBox_5, 5, 3, 1, 1)
        self.comboBox_6 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.gridLayout.addWidget(self.comboBox_6, 6, 3, 1, 1)
        self.comboBox_7 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.gridLayout.addWidget(self.comboBox_7, 7, 3, 1, 1)
        self.comboBox_9 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.gridLayout.addWidget(self.comboBox_9, 9, 3, 1, 1)
        self.comboBox_10 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_10.setObjectName("comboBox_10")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.gridLayout.addWidget(self.comboBox_10, 10, 3, 1, 1)
        self.comboBox_8 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.gridLayout.addWidget(self.comboBox_8, 8, 3, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_5.sizePolicy().hasHeightForWidth())
        self.lineEdit_5.setSizePolicy(sizePolicy)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout.addWidget(self.lineEdit_5, 5, 2, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 1, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 14, 3, 1, 1)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_12.sizePolicy().hasHeightForWidth())
        self.lineEdit_12.setSizePolicy(sizePolicy)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.gridLayout.addWidget(self.lineEdit_12, 12, 2, 1, 1)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_13.sizePolicy().hasHeightForWidth())
        self.lineEdit_13.setSizePolicy(sizePolicy)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.gridLayout.addWidget(self.lineEdit_13, 13, 2, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(10, 610, 176, 30))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Technical Complexity Factor (TCF)"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Weight</span></p></body></html>"))
        self.label_73.setText(_translate("Dialog", "<html><head/><body><p>Special user training <br/>facilities are required</p></body></html>"))
        self.label_68.setText(_translate("Dialog", "<html><head/><body><p>Provides direct access <br/>for third parties</p></body></html>"))
        self.label_32.setText(_translate("Dialog", "<html><head/><body><p>T5</p></body></html>"))
        self.label_12.setText(_translate("Dialog", "T1"))
        self.label_72.setText(_translate("Dialog", "T13"))
        self.label_67.setText(_translate("Dialog", "T12"))
        self.label_62.setText(_translate("Dialog", "T11"))
        self.label_13.setText(_translate("Dialog", "Distributed System"))
        self.label_63.setText(_translate("Dialog", "<html><head/><body><p>Special security <br/>features</p></body></html>"))
        self.comboBox.setItemText(0, _translate("Dialog", "0"))
        self.comboBox.setItemText(1, _translate("Dialog", "1"))
        self.comboBox.setItemText(2, _translate("Dialog", "2"))
        self.comboBox.setItemText(3, _translate("Dialog", "3"))
        self.comboBox.setItemText(4, _translate("Dialog", "4"))
        self.comboBox.setItemText(5, _translate("Dialog", "5"))
        self.comboBox_2.setItemText(0, _translate("Dialog", "0"))
        self.comboBox_2.setItemText(1, _translate("Dialog", "1"))
        self.comboBox_2.setItemText(2, _translate("Dialog", "2"))
        self.comboBox_2.setItemText(3, _translate("Dialog", "3"))
        self.comboBox_2.setItemText(4, _translate("Dialog", "4"))
        self.comboBox_2.setItemText(5, _translate("Dialog", "5"))
        self.label_7.setText(_translate("Dialog", "<html><head/><body><p>0</p></body></html>"))
        self.label_43.setText(_translate("Dialog", "Easy to use"))
        self.label_23.setText(_translate("Dialog", "End User Efficiency"))
        self.label_27.setText(_translate("Dialog", "T4"))
        self.label_28.setText(_translate("Dialog", "<html><head/><body><p>Complex internal <br/>Processing</p></body></html>"))
        self.label_42.setText(_translate("Dialog", "T7"))
        self.label_22.setText(_translate("Dialog", "T3"))
        self.label_17.setText(_translate("Dialog", "T2"))
        self.label_38.setText(_translate("Dialog", "Easy to install"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Description</span></p></body></html>"))
        self.label_5.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Calculated Factor</span><br/><span style=\" font-size:9pt; color:#707070;\">(weight*perceived complexity)</span></p></body></html>"))
        self.label_58.setText(_translate("Dialog", "Concurrent"))
        self.label_48.setText(_translate("Dialog", "Portable"))
        self.label_20.setText(_translate("Dialog", "<html><head/><body><p>0</p></body></html>"))
        self.label_24.setText(_translate("Dialog", "<html><head/><body><p>0</p></body></html>"))
        self.label_25.setText(_translate("Dialog", "<html><head/><body><p>0</p></body></html>"))
        self.label_29.setText(_translate("Dialog", "<html><head/><body><p>0</p></body></html>"))
        self.label_30.setText(_translate("Dialog", "<html><head/><body><p>0</p></body></html>"))
        self.label_34.setText(_translate("Dialog", "<html><head/><body><p>0</p></body></html>"))
        self.label_35.setText(_translate("Dialog", "<html><head/><body><p>0</p></body></html>"))
        self.label_52.setText(_translate("Dialog", "T9"))
        self.label_57.setText(_translate("Dialog", "T10"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Technical Factor </span></p></body></html>"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Perceived Complexity</span></p></body></html>"))
        self.label_47.setText(_translate("Dialog", "T8"))
        self.label_33.setText(_translate("Dialog", "<html><head/><body><p>Reusability</p></body></html>"))
        self.label_37.setText(_translate("Dialog", "T6"))
        self.label_18.setText(_translate("Dialog", "Performance"))
        self.comboBox_11.setItemText(0, _translate("Dialog", "0"))
        self.comboBox_11.setItemText(1, _translate("Dialog", "1"))
        self.comboBox_11.setItemText(2, _translate("Dialog", "2"))
        self.comboBox_11.setItemText(3, _translate("Dialog", "3"))
        self.comboBox_11.setItemText(4, _translate("Dialog", "4"))
        self.comboBox_11.setItemText(5, _translate("Dialog", "5"))
        self.comboBox_12.setItemText(0, _translate("Dialog", "0"))
        self.comboBox_12.setItemText(1, _translate("Dialog", "1"))
        self.comboBox_12.setItemText(2, _translate("Dialog", "2"))
        self.comboBox_12.setItemText(3, _translate("Dialog", "3"))
        self.comboBox_12.setItemText(4, _translate("Dialog", "4"))
        self.comboBox_12.setItemText(5, _translate("Dialog", "5"))
        self.comboBox_13.setItemText(0, _translate("Dialog", "0"))
        self.comboBox_13.setItemText(1, _translate("Dialog", "1"))
        self.comboBox_13.setItemText(2, _translate("Dialog", "2"))
        self.comboBox_13.setItemText(3, _translate("Dialog", "3"))
        self.comboBox_13.setItemText(4, _translate("Dialog", "4"))
        self.comboBox_13.setItemText(5, _translate("Dialog", "5"))
        self.label_8.setText(_translate("Dialog", "<html><head/><body><p>0</p></body></html>"))
        self.label_9.setText(_translate("Dialog", "<html><head/><body><p>0</p></body></html>"))
        self.label_10.setText(_translate("Dialog", "<html><head/><body><p>0</p></body></html>"))
        self.label_14.setText(_translate("Dialog", "<html><head/><body><p>0</p></body></html>"))
        self.label_15.setText(_translate("Dialog", "<html><head/><body><p>0</p></body></html>"))
        self.label_19.setText(_translate("Dialog", "<html><head/><body><p>0</p></body></html>"))
        self.label_53.setText(_translate("Dialog", "Easy to change"))
        self.comboBox_3.setItemText(0, _translate("Dialog", "0"))
        self.comboBox_3.setItemText(1, _translate("Dialog", "1"))
        self.comboBox_3.setItemText(2, _translate("Dialog", "2"))
        self.comboBox_3.setItemText(3, _translate("Dialog", "3"))
        self.comboBox_3.setItemText(4, _translate("Dialog", "4"))
        self.comboBox_3.setItemText(5, _translate("Dialog", "5"))
        self.comboBox_4.setItemText(0, _translate("Dialog", "0"))
        self.comboBox_4.setItemText(1, _translate("Dialog", "1"))
        self.comboBox_4.setItemText(2, _translate("Dialog", "2"))
        self.comboBox_4.setItemText(3, _translate("Dialog", "3"))
        self.comboBox_4.setItemText(4, _translate("Dialog", "4"))
        self.comboBox_4.setItemText(5, _translate("Dialog", "5"))
        self.comboBox_5.setItemText(0, _translate("Dialog", "0"))
        self.comboBox_5.setItemText(1, _translate("Dialog", "1"))
        self.comboBox_5.setItemText(2, _translate("Dialog", "2"))
        self.comboBox_5.setItemText(3, _translate("Dialog", "3"))
        self.comboBox_5.setItemText(4, _translate("Dialog", "4"))
        self.comboBox_5.setItemText(5, _translate("Dialog", "5"))
        self.comboBox_6.setItemText(0, _translate("Dialog", "0"))
        self.comboBox_6.setItemText(1, _translate("Dialog", "1"))
        self.comboBox_6.setItemText(2, _translate("Dialog", "2"))
        self.comboBox_6.setItemText(3, _translate("Dialog", "3"))
        self.comboBox_6.setItemText(4, _translate("Dialog", "4"))
        self.comboBox_6.setItemText(5, _translate("Dialog", "5"))
        self.comboBox_7.setItemText(0, _translate("Dialog", "0"))
        self.comboBox_7.setItemText(1, _translate("Dialog", "1"))
        self.comboBox_7.setItemText(2, _translate("Dialog", "2"))
        self.comboBox_7.setItemText(3, _translate("Dialog", "3"))
        self.comboBox_7.setItemText(4, _translate("Dialog", "4"))
        self.comboBox_7.setItemText(5, _translate("Dialog", "5"))
        self.comboBox_9.setItemText(0, _translate("Dialog", "0"))
        self.comboBox_9.setItemText(1, _translate("Dialog", "1"))
        self.comboBox_9.setItemText(2, _translate("Dialog", "2"))
        self.comboBox_9.setItemText(3, _translate("Dialog", "3"))
        self.comboBox_9.setItemText(4, _translate("Dialog", "4"))
        self.comboBox_9.setItemText(5, _translate("Dialog", "5"))
        self.comboBox_10.setItemText(0, _translate("Dialog", "0"))
        self.comboBox_10.setItemText(1, _translate("Dialog", "1"))
        self.comboBox_10.setItemText(2, _translate("Dialog", "2"))
        self.comboBox_10.setItemText(3, _translate("Dialog", "3"))
        self.comboBox_10.setItemText(4, _translate("Dialog", "4"))
        self.comboBox_10.setItemText(5, _translate("Dialog", "5"))
        self.comboBox_8.setItemText(0, _translate("Dialog", "0"))
        self.comboBox_8.setItemText(1, _translate("Dialog", "1"))
        self.comboBox_8.setItemText(2, _translate("Dialog", "2"))
        self.comboBox_8.setItemText(3, _translate("Dialog", "3"))
        self.comboBox_8.setItemText(4, _translate("Dialog", "4"))
        self.comboBox_8.setItemText(5, _translate("Dialog", "5"))
        self.label_6.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Total Factor</span></p></body></html>"))
