# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/val_adj_fac.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialog(object):
    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.resize(764, 594)
        self.pushButton = QtWidgets.QPushButton(dialog)
        self.pushButton.setGeometry(QtCore.QRect(10, 550, 95, 30))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(110, 550, 95, 30))
        self.pushButton_2.setObjectName("pushButton_2")
        self.layoutWidget = QtWidgets.QWidget(dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 11, 732, 526))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox_14 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_14.setObjectName("comboBox_14")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.gridLayout.addWidget(self.comboBox_14, 14, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 8, 0, 1, 1)
        self.comboBox_4 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.gridLayout.addWidget(self.comboBox_4, 4, 1, 1, 1)
        self.comboBox_9 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.gridLayout.addWidget(self.comboBox_9, 9, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 13, 0, 1, 1)
        self.comboBox_10 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_10.setObjectName("comboBox_10")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.gridLayout.addWidget(self.comboBox_10, 10, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 14, 0, 1, 1)
        self.comboBox_13 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_13.setObjectName("comboBox_13")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.gridLayout.addWidget(self.comboBox_13, 13, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 6, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 11, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 9, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.comboBox_8 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.gridLayout.addWidget(self.comboBox_8, 8, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.comboBox_7 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.gridLayout.addWidget(self.comboBox_7, 7, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 10, 0, 1, 1)
        self.comboBox_6 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.gridLayout.addWidget(self.comboBox_6, 6, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 7, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout.addWidget(self.comboBox_2, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.comboBox_11 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_11.setObjectName("comboBox_11")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.gridLayout.addWidget(self.comboBox_11, 11, 1, 1, 1)
        self.comboBox_12 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_12.setObjectName("comboBox_12")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.gridLayout.addWidget(self.comboBox_12, 12, 1, 1, 1)
        self.comboBox_5 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.gridLayout.addWidget(self.comboBox_5, 5, 1, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 1, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 12, 0, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.gridLayout.addWidget(self.comboBox_3, 3, 1, 1, 1)

        self.retranslateUi(dialog)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "Value Adjustment Factors"))
        self.pushButton.setText(_translate("dialog", "Done"))
        self.pushButton_2.setText(_translate("dialog", "Cancel"))
        self.comboBox_14.setItemText(0, _translate("dialog", "0"))
        self.comboBox_14.setItemText(1, _translate("dialog", "1"))
        self.comboBox_14.setItemText(2, _translate("dialog", "2"))
        self.comboBox_14.setItemText(3, _translate("dialog", "3"))
        self.comboBox_14.setItemText(4, _translate("dialog", "4"))
        self.comboBox_14.setItemText(5, _translate("dialog", "5"))
        self.label_9.setText(_translate("dialog", "Are the internal logical files updated on-line?"))
        self.comboBox_4.setItemText(0, _translate("dialog", "0"))
        self.comboBox_4.setItemText(1, _translate("dialog", "1"))
        self.comboBox_4.setItemText(2, _translate("dialog", "2"))
        self.comboBox_4.setItemText(3, _translate("dialog", "3"))
        self.comboBox_4.setItemText(4, _translate("dialog", "4"))
        self.comboBox_4.setItemText(5, _translate("dialog", "5"))
        self.comboBox_9.setItemText(0, _translate("dialog", "0"))
        self.comboBox_9.setItemText(1, _translate("dialog", "1"))
        self.comboBox_9.setItemText(2, _translate("dialog", "2"))
        self.comboBox_9.setItemText(3, _translate("dialog", "3"))
        self.comboBox_9.setItemText(4, _translate("dialog", "4"))
        self.comboBox_9.setItemText(5, _translate("dialog", "5"))
        self.label_14.setText(_translate("dialog", "Is the system designed for multiple installations in different organizations?"))
        self.comboBox_10.setItemText(0, _translate("dialog", "0"))
        self.comboBox_10.setItemText(1, _translate("dialog", "1"))
        self.comboBox_10.setItemText(2, _translate("dialog", "2"))
        self.comboBox_10.setItemText(3, _translate("dialog", "3"))
        self.comboBox_10.setItemText(4, _translate("dialog", "4"))
        self.comboBox_10.setItemText(5, _translate("dialog", "5"))
        self.label_15.setText(_translate("dialog", "Is the application designed to facilitate change and for ease of use by the user?"))
        self.comboBox_13.setItemText(0, _translate("dialog", "0"))
        self.comboBox_13.setItemText(1, _translate("dialog", "1"))
        self.comboBox_13.setItemText(2, _translate("dialog", "2"))
        self.comboBox_13.setItemText(3, _translate("dialog", "3"))
        self.comboBox_13.setItemText(4, _translate("dialog", "4"))
        self.comboBox_13.setItemText(5, _translate("dialog", "5"))
        self.label_7.setText(_translate("dialog", "Does the system require on-line data entry?"))
        self.label_12.setText(_translate("dialog", "Is the code designed to be reusable?"))
        self.label_10.setText(_translate("dialog", "Are the inputs, outputs, files, or inquiries complex?"))
        self.label.setText(_translate("dialog", "As a value from 0 to 5 for each of the following Value Adjustment Factors: "))
        self.comboBox_8.setItemText(0, _translate("dialog", "0"))
        self.comboBox_8.setItemText(1, _translate("dialog", "1"))
        self.comboBox_8.setItemText(2, _translate("dialog", "2"))
        self.comboBox_8.setItemText(3, _translate("dialog", "3"))
        self.comboBox_8.setItemText(4, _translate("dialog", "4"))
        self.comboBox_8.setItemText(5, _translate("dialog", "5"))
        self.label_6.setText(_translate("dialog", "Will the system run in existing,heavy utilized operational environment?"))
        self.comboBox_7.setItemText(0, _translate("dialog", "0"))
        self.comboBox_7.setItemText(1, _translate("dialog", "1"))
        self.comboBox_7.setItemText(2, _translate("dialog", "2"))
        self.comboBox_7.setItemText(3, _translate("dialog", "3"))
        self.comboBox_7.setItemText(4, _translate("dialog", "4"))
        self.comboBox_7.setItemText(5, _translate("dialog", "5"))
        self.label_2.setText(_translate("dialog", "Does the system require reliable backup and recovery?"))
        self.label_3.setText(_translate("dialog", "Are specialized data communications required to transfer information to or from the application"))
        self.label_11.setText(_translate("dialog", "Is the internal processing complex?"))
        self.comboBox_6.setItemText(0, _translate("dialog", "0"))
        self.comboBox_6.setItemText(1, _translate("dialog", "1"))
        self.comboBox_6.setItemText(2, _translate("dialog", "2"))
        self.comboBox_6.setItemText(3, _translate("dialog", "3"))
        self.comboBox_6.setItemText(4, _translate("dialog", "4"))
        self.comboBox_6.setItemText(5, _translate("dialog", "5"))
        self.label_8.setText(_translate("dialog", "Does the on-line data entry require the input transaction to be built over multiple screens or operations?"))
        self.comboBox_2.setItemText(0, _translate("dialog", "0"))
        self.comboBox_2.setItemText(1, _translate("dialog", "1"))
        self.comboBox_2.setItemText(2, _translate("dialog", "2"))
        self.comboBox_2.setItemText(3, _translate("dialog", "3"))
        self.comboBox_2.setItemText(4, _translate("dialog", "4"))
        self.comboBox_2.setItemText(5, _translate("dialog", "5"))
        self.label_5.setText(_translate("dialog", "Is performance critical?"))
        self.label_4.setText(_translate("dialog", "Are there distributed processing functions?"))
        self.comboBox_11.setItemText(0, _translate("dialog", "0"))
        self.comboBox_11.setItemText(1, _translate("dialog", "1"))
        self.comboBox_11.setItemText(2, _translate("dialog", "2"))
        self.comboBox_11.setItemText(3, _translate("dialog", "3"))
        self.comboBox_11.setItemText(4, _translate("dialog", "4"))
        self.comboBox_11.setItemText(5, _translate("dialog", "5"))
        self.comboBox_12.setItemText(0, _translate("dialog", "0"))
        self.comboBox_12.setItemText(1, _translate("dialog", "1"))
        self.comboBox_12.setItemText(2, _translate("dialog", "2"))
        self.comboBox_12.setItemText(3, _translate("dialog", "3"))
        self.comboBox_12.setItemText(4, _translate("dialog", "4"))
        self.comboBox_12.setItemText(5, _translate("dialog", "5"))
        self.comboBox_5.setItemText(0, _translate("dialog", "0"))
        self.comboBox_5.setItemText(1, _translate("dialog", "1"))
        self.comboBox_5.setItemText(2, _translate("dialog", "2"))
        self.comboBox_5.setItemText(3, _translate("dialog", "3"))
        self.comboBox_5.setItemText(4, _translate("dialog", "4"))
        self.comboBox_5.setItemText(5, _translate("dialog", "5"))
        self.comboBox.setItemText(0, _translate("dialog", "0"))
        self.comboBox.setItemText(1, _translate("dialog", "1"))
        self.comboBox.setItemText(2, _translate("dialog", "2"))
        self.comboBox.setItemText(3, _translate("dialog", "3"))
        self.comboBox.setItemText(4, _translate("dialog", "4"))
        self.comboBox.setItemText(5, _translate("dialog", "5"))
        self.label_13.setText(_translate("dialog", "Are conversion and installation included in the design?"))
        self.comboBox_3.setItemText(0, _translate("dialog", "0"))
        self.comboBox_3.setItemText(1, _translate("dialog", "1"))
        self.comboBox_3.setItemText(2, _translate("dialog", "2"))
        self.comboBox_3.setItemText(3, _translate("dialog", "3"))
        self.comboBox_3.setItemText(4, _translate("dialog", "4"))
        self.comboBox_3.setItemText(5, _translate("dialog", "5"))
